//go:build linux

package netident

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// DHCP configuration drop-in paths for various DHCP clients.
const (
	dhclientConfDir = "/etc/dhcp/dhclient.conf.d"
	dhclientConf    = "/etc/dhcp/dhclient.conf"
	nmDispatchDir   = "/etc/NetworkManager/conf.d"
	dropinName      = "90-idspoof-persona.conf"
)

// applyDHCP configures the DHCP client to announce the persona hostname
// and optionally the vendor class (Option 60). This makes DHCP fingerprinting
// tools (fingerbank, etc.) see the target OS without changing the actual
// system hostname.
func applyDHCP(p *Persona, snap *Snapshot) error {
	if p.Hostname == "" {
		return nil
	}

	// Try NetworkManager first (most modern distros).
	if nmActive() {
		return applyDHCPNetworkManager(p, snap)
	}

	// Fall back to dhclient.
	return applyDHCPDhclient(p, snap)
}

// applyDHCPNetworkManager creates a NetworkManager conf.d dropin that sets
// the DHCP hostname and optionally the vendor class without touching the
// system hostname.
func applyDHCPNetworkManager(p *Persona, snap *Snapshot) error {
	os.MkdirAll(nmDispatchDir, 0o755)

	content := fmt.Sprintf(`# Generated by ID-Spoofer — %s DHCP persona
# Announces %s-style hostname via DHCP without changing system hostname.
[connection]
# Prevent NM from sending the real hostname.

[ipv4]
dhcp-send-hostname=yes
dhcp-hostname=%s
`, p.Type, p.Type, p.Hostname)

	path := filepath.Join(nmDispatchDir, dropinName)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing NM dropin: %w", err)
	}

	snap.DHCPConfigModified = path

	// Vendor class hook (Option 60) — only for personas that use it (Windows).
	hookDir := "/etc/dhcp/dhclient-enter-hooks.d"
	hookPath := filepath.Join(hookDir, "idspoof-vendor")
	if p.DHCPVendorClass != "" {
		os.MkdirAll(hookDir, 0o755)
		hookContent := fmt.Sprintf(`#!/bin/sh
# ID-Spoofer: send %s DHCP vendor class identifier
new_vendor_class_identifier="%s"
`, p.Type, p.DHCPVendorClass)
		os.WriteFile(hookPath, []byte(hookContent), 0o755)
	} else {
		// Remove any existing vendor hook from a previous Windows persona.
		os.Remove(hookPath)
	}

	// Reload NM to pick up new config.
	exec.Command("nmcli", "general", "reload").Run()

	return nil
}

// applyDHCPDhclient modifies dhclient.conf directly.
func applyDHCPDhclient(p *Persona, snap *Snapshot) error {
	if _, err := os.Stat(dhclientConf); os.IsNotExist(err) {
		// No dhclient.conf to modify.
		return nil
	}

	// Back up original.
	backup := dhclientConf + ".idspoof.bak"
	if _, err := os.Stat(backup); os.IsNotExist(err) {
		data, err := os.ReadFile(dhclientConf)
		if err == nil {
			os.WriteFile(backup, data, 0o644)
		}
	}
	snap.DHCPConfigBackup = backup

	// Read existing config.
	data, err := os.ReadFile(dhclientConf)
	if err != nil {
		return fmt.Errorf("reading dhclient.conf: %w", err)
	}

	// Append our settings (idempotent — check for marker).
	marker := "# BEGIN ID-Spoofer persona"
	if strings.Contains(string(data), marker) {
		return nil // Already configured.
	}

	addition := fmt.Sprintf("\n%s\nsend host-name \"%s\";\n", marker, p.Hostname)
	if p.DHCPVendorClass != "" {
		addition += fmt.Sprintf("send vendor-class-identifier \"%s\";\n", p.DHCPVendorClass)
	}
	addition += "# END ID-Spoofer persona\n"

	if err := os.WriteFile(dhclientConf, append(data, []byte(addition)...), 0o644); err != nil {
		return fmt.Errorf("writing dhclient.conf: %w", err)
	}

	snap.DHCPConfigModified = dhclientConf
	return nil
}

// restoreDHCP removes DHCP modifications.
func restoreDHCP(snap *Snapshot) {
	// Remove NM dropin (current and legacy names).
	os.Remove(filepath.Join(nmDispatchDir, dropinName))
	os.Remove(filepath.Join(nmDispatchDir, "90-idspoof-windows.conf")) // v2.0.0 compat

	// Remove dhclient hook.
	hookPath := "/etc/dhcp/dhclient-enter-hooks.d/idspoof-vendor"
	os.Remove(hookPath)

	// Restore dhclient.conf from backup.
	if snap.DHCPConfigBackup != "" {
		if data, err := os.ReadFile(snap.DHCPConfigBackup); err == nil {
			os.WriteFile(dhclientConf, data, 0o644)
			os.Remove(snap.DHCPConfigBackup)
		}
	}

	// Reload NM if active.
	if nmActive() {
		exec.Command("nmcli", "general", "reload").Run()
	}
}

func nmActive() bool {
	return exec.Command("nmcli", "general", "status").Run() == nil
}
